roots = [
    '''^Main\.main$''',
    '''^Paths_\.*''',
    # Modules that have “independent” APIs (but should probably get tests and/or extracted to independent repos).
    '''^EasyTest\.[^\.]+$''',
    '''^System\.Path\.[^\.]+$''',
    '''^Unison\.Util\.Alphabetical\.[^\.]+$''',
    '''^Unison\.Util\.BiMultimap\.[^\.]+$''',
    '''^Unison\.Util\.Bytes\.[^\.]+$''',
    '''^Unison\.Util\.ColorText\.[^\.]+$''',
    '''^Unison\.Util\.EnumContainers\.[^\.]+$''',
    '''^Unison\.Util\.List\.[^\.]+$''',
    '''^Unison\.Util\.Logger\.[^\.]+$''',
    '''^Unison\.Util\.Map\.[^\.]+$''',
    '''^Unison\.Util\.Monoid\.[^\.]+$''',
    '''^Unison\.Util\.Pretty\.[^\.]+$''',
    '''^Unison\.Util\.Range\.[^\.]+$''',
    '''^Unison\.Util\.Recursion\.[^\.]+$''',
    '''^Unison\.Util\.Relation\.[^\.]+$''',
    '''^Unison\.Util\.Relation3\.[^\.]+$''',
    '''^Unison\.Util\.Relation4\.[^\.]+$''',
    '''^Unison\.Util\.Rope\.[^\.]+$''',
    # Template Haskell (which Weeder can’t identify usage of)
    '''^Unison\.Sqlite\.Sql.sql$''',
    # Debugging tools – not used in production, but often enabled during development.
    '''^Unison\.Debug\.[^\.]+$''',
    '''^Unison\.Prelude\.wundefined$''',
    '''^Unison\.Runtime\.Debug\.[^\.]+$''',
    '''^Unison\.Syntax\.Lexer\.Unison\.debugFilePreParse$''',
]
type-class-roots = true
unused-types = true
